# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef46b7faecb1e71642dafcbc18bf2852128c34e5545a14a740112a0e12ba0251066ffcf4b75470bda8c537eed066a6510f3c919f15de86491c5332f81218502e

test:
  secret_key_base: c4a00c58658365449246dc4f5b710701fec794338ef3aca1a017390f4b96d42b9111b4bbe1ae30936edc5837f432dbbfde60177b8890625049a8e927a8e62714

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
